### ISSUE TITLE
[Class01 HW#1] Github Issue 실습 - 감다공

### ISSUE THREAD

**Issue by bluenight12** [pskcci/intel-01#14]
- [x]  Issue ticket을 생성하고 다음 내용을 작성

  * Name: 감다공
  * Github ID: bluenight12
  * My repo: https://github.com/bluenight12/intel_project

- [x] Assignee를 본인에게 할당
- [x] Milestone을 "[Class01 HW#1] Github Issue 실습"으로 설정

**Comment by elddy0948** [comment]
!
